### ISSUE TITLE
Principal not principle

### ISSUE THREAD

**Issue by ValerieHMoore** [learn-co-curriculum/html-introduction#2]
Hope I'm not being a pain, here's another spelling error:
"A well structured article will generally have its principle arguments bracketed by low-number header tags..." -- should be principal, not principle.

Thank you.

**Comment by Sdcrouse** [comment]
Hi. I'm only a student myself, but I sent them a pull request to fix that. There was also a little typo further in the document ("techonologists" instead of "technologists").

**Comment by drakeltheryuujin** [comment]
Fixed. Thanks! 💙
