### ISSUE TITLE
Inaccurate information in the Headers section

### ISSUE THREAD

**Issue by Sdcrouse** [learn-co-curriculum/html-introduction#4]
Hi. The Headers section mentions that "as Avi pointed out, when we provide semantic markup, machines can infer the "main points" of a page." In the video at the top of the lesson, I think Avi does mention semantic markup or something similar. However, nowhere does he mention machines inferring the main points of a page.

Maybe this lesson was referencing another video?

Either way, thanks for checking this out!

Sdcrouse

**Comment by drakeltheryuujin** [comment]
Hi @Sdcrouse,

Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
